"""place_tag tablosuna cascade eklendi

Revision ID: e763321906cf
Revises: 9d4e2f1a87b3
Create Date: 2026-05-21 13:52:40.187688+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'e763321906cf'
down_revision: Union[str, None] = '9d4e2f1a87b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
