"""initial schema

Revision ID: 46aad6190614
Revises: 
Create Date: 2026-05-11 12:32:51.038516+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

revision: str = '46aad6190614'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_decision_queue',
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_place_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('reason', sa.Enum('low_confidence', 'missing_field', 'conflict', 'geofence', name='ai_decision_reason'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processed', 'approved', 'rejected', 'merged', 'retry', name='ai_decision_status'), server_default='pending', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_decision_queue'))
    )
    op.create_index(op.f('ix_ai_decision_queue_status'), 'ai_decision_queue', ['status'], unique=False)
    op.create_table('etl_run_log',
    sa.Column('dag_id', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('records_extracted', sa.Integer(), nullable=True),
    sa.Column('records_loaded', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etl_run_log')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_etl_run_log_idempotency_key'))
    )
    op.create_index(op.f('ix_etl_run_log_dag_id'), 'etl_run_log', ['dag_id'], unique=False)
    op.create_geospatial_table('places',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('isim', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kategori', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('koordinat', Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('bbox', Geography(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('ziyaret_bilgisi', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('etiketler', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('tarihi_yapim_yili', sa.Integer(), nullable=True),
    sa.Column('unesco', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('kapak_foto_url', sa.Text(), nullable=True),
    sa.Column('aciklama', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aciklama_source', sa.String(length=64), nullable=True),
    sa.Column('kaynak_atif', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kalite_skoru', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('merged_from', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places'))
    )
    op.create_geospatial_index('ix_places_bbox_gist', 'places', ['bbox'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('ix_places_etiketler_gin', 'places', ['etiketler'], unique=False, postgresql_using='gin')
    op.create_index('ix_places_isim_gin', 'places', ['isim'], unique=False, postgresql_using='gin', postgresql_ops={'isim': 'jsonb_path_ops'})
    op.create_index('ix_places_kategori_gin', 'places', ['kategori'], unique=False, postgresql_using='gin')
    op.create_geospatial_index('ix_places_koordinat_gist', 'places', ['koordinat'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_places_slug'), 'places', ['slug'], unique=True)
    op.create_index('ix_places_updated_at_desc', 'places', [sa.text('updated_at DESC')], unique=False)
    op.create_table('tags',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('group', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_group'), 'tags', ['group'], unique=False)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('username', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), server_default='user', nullable=False),
    sa.Column('locale', sa.String(length=8), server_default='tr', nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('kvkk_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("birth_date <= (CURRENT_DATE - INTERVAL '18 years')", name=op.f('ck_users_adult_birth_date')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ai_decision_log',
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.Column('model_provider', sa.Enum('gemini', 'groq', 'openrouter', 'mistral', name='ai_model_provider'), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('prompt_hash', sa.String(length=128), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', sa.Enum('merge', 'split', 'reject', name='ai_decision_type'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['ai_decision_queue.id'], name=op.f('fk_ai_decision_log_queue_id_ai_decision_queue'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_decision_log'))
    )
    op.create_index(op.f('ix_ai_decision_log_prompt_hash'), 'ai_decision_log', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_ai_decision_log_queue_id'), 'ai_decision_log', ['queue_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_target_id'), 'audit_log', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_log_target_type'), 'audit_log', ['target_type'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_favorites_place_id_places'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'place_id', name=op.f('pk_favorites'))
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followee_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> followee_id', name=op.f('ck_follows_no_self_follow')),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], name=op.f('fk_follows_followee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_follows_follower_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id', name=op.f('pk_follows'))
    )
    op.create_table('merge_decision_log',
    sa.Column('etl_run_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('source_record_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('geo_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('name_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('category_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('primary_source_per_field', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run_log.id'], name=op.f('fk_merge_decision_log_etl_run_id_etl_run_log'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_merge_decision_log_place_id_places'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merge_decision_log'))
    )
    op.create_index(op.f('ix_merge_decision_log_etl_run_id'), 'merge_decision_log', ['etl_run_id'], unique=False)
    op.create_index(op.f('ix_merge_decision_log_place_id'), 'merge_decision_log', ['place_id'], unique=False)
    op.create_table('opening_hours',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('season_start', sa.Date(), nullable=True),
    sa.Column('season_end', sa.Date(), nullable=True),
    sa.Column('is_closed_special', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.Enum('bizizmir', 'osm', 'llm', 'scrape', name='opening_hours_source'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name=op.f('ck_opening_hours_day_of_week_range')),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_opening_hours_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opening_hours'))
    )
    op.create_index(op.f('ix_opening_hours_place_id'), 'opening_hours', ['place_id'], unique=False)
    op.create_table('place_tags',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_place_tags_place_id_places'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_place_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id', 'tag_id', name=op.f('pk_place_tags'))
    )
    op.create_table('reports',
    sa.Column('target_type', sa.Enum('place', 'photo', 'review', 'route', 'user', name='report_target_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('auto_resolved', 'escalated', 'dismissed', name='report_status'), server_default='auto_resolved', nullable=False),
    sa.Column('auto_action', sa.Enum('hidden', 'none', name='report_auto_action'), server_default='none', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_target_id'), 'reports', ['target_id'], unique=False)
    op.create_index(op.f('ix_reports_target_type'), 'reports', ['target_type'], unique=False)
    op.create_table('reviews',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('visited_at', sa.Date(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('toxicity_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_reviews_place_id_places'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index(op.f('ix_reviews_place_id'), 'reviews', ['place_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('routes',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('est_duration_min', sa.Integer(), nullable=True),
    sa.Column('total_distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'moderate', 'hard', name='route_difficulty'), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_routes_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routes'))
    )
    op.create_index(op.f('ix_routes_owner_id'), 'routes', ['owner_id'], unique=False)
    op.create_table('photos',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('thumb_url', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exif', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('license', sa.String(length=64), server_default='CC BY-NC 4.0', nullable=False),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('nsfw_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('phash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_photos_place_id_places'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_photos_route_id_routes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_photos_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    op.create_index(op.f('ix_photos_phash'), 'photos', ['phash'], unique=False)
    op.create_index(op.f('ix_photos_place_id'), 'photos', ['place_id'], unique=False)
    op.create_index(op.f('ix_photos_route_id'), 'photos', ['route_id'], unique=False)
    op.create_index(op.f('ix_photos_user_id'), 'photos', ['user_id'], unique=False)
    op.create_table('route_comments',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_comments_route_id_routes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_route_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_comments'))
    )
    op.create_index(op.f('ix_route_comments_route_id'), 'route_comments', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_comments_user_id'), 'route_comments', ['user_id'], unique=False)
    op.create_table('route_likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_likes_route_id_routes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_route_likes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'route_id', name=op.f('pk_route_likes'))
    )
    op.create_table('route_stops',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_duration_min', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_route_stops_place_id_places'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('fk_route_stops_route_id_routes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stops')),
    sa.UniqueConstraint('route_id', 'order_index', name='route_order')
    )
    op.create_index(op.f('ix_route_stops_place_id'), 'route_stops', ['place_id'], unique=False)
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_place_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_table('route_likes')
    op.drop_index(op.f('ix_route_comments_user_id'), table_name='route_comments')
    op.drop_index(op.f('ix_route_comments_route_id'), table_name='route_comments')
    op.drop_table('route_comments')
    op.drop_index(op.f('ix_photos_user_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_route_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_place_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_phash'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_routes_owner_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_place_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reports_target_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_target_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('place_tags')
    op.drop_index(op.f('ix_opening_hours_place_id'), table_name='opening_hours')
    op.drop_table('opening_hours')
    op.drop_index(op.f('ix_merge_decision_log_place_id'), table_name='merge_decision_log')
    op.drop_index(op.f('ix_merge_decision_log_etl_run_id'), table_name='merge_decision_log')
    op.drop_table('merge_decision_log')
    op.drop_table('follows')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_audit_log_target_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_target_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_ai_decision_log_queue_id'), table_name='ai_decision_log')
    op.drop_index(op.f('ix_ai_decision_log_prompt_hash'), table_name='ai_decision_log')
    op.drop_table('ai_decision_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_index(op.f('ix_tags_group'), table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_places_updated_at_desc', table_name='places')
    op.drop_index(op.f('ix_places_slug'), table_name='places')
    op.drop_geospatial_index('ix_places_koordinat_gist', table_name='places', postgresql_using='gist', column_name='koordinat')
    op.drop_index('ix_places_kategori_gin', table_name='places', postgresql_using='gin')
    op.drop_index('ix_places_isim_gin', table_name='places', postgresql_using='gin', postgresql_ops={'isim': 'jsonb_path_ops'})
    op.drop_index('ix_places_etiketler_gin', table_name='places', postgresql_using='gin')
    op.drop_geospatial_index('ix_places_bbox_gist', table_name='places', postgresql_using='gist', column_name='bbox')
    op.drop_geospatial_table('places')
    op.drop_index(op.f('ix_etl_run_log_dag_id'), table_name='etl_run_log')
    op.drop_table('etl_run_log')
    op.drop_index(op.f('ix_ai_decision_queue_status'), table_name='ai_decision_queue')
    op.drop_table('ai_decision_queue')
    # ### end Alembic commands ###
